export const agentsTemplate = `
# Pipes SDK Agent Playbook

Use this file to help a coding agent deliver a working Pipes SDK pipeline quickly and safely.
It is intentionally concise, with examples at the end.

## Mission
Ship a pipeline that:
- Builds from the generated project structure
- Streams from SQD Portal
- Decodes/transforms only what is required
- Persists correctly with rollback safety

## Success criteria
- \`src/index.ts\` runs without edits outside \`src/\`
- Decoding matches the chosen network (EVM or Solana)
- Data is persisted with proper rollback handling
- Ranges and queries are minimal and scoped

## Project map
- \`src/index.ts\`: main pipeline entry
- \`src/contracts/\`: generated ABIs and typed decoders
- \`src/utils/\`: ClickHouse helpers (only when ClickHouse target is chosen)
- \`migrations/\`: SQL for ClickHouse or PostgreSQL
- \`.env\`, \`docker-compose.yml\`: local databases and credentials

## Decide the mode first
This project is either:
- **EVM**: uses \`@subsquid/pipes/evm\`
- **Solana**: uses \`@subsquid/pipes/solana\`

Check \`src/index.ts\` imports and the generated template before making changes.

## Core pipeline shape
Pipes SDK is a stream:
1) **Portal source**: fetches chain data; declares its decoder(s) under \`outputs:\` and a stable \`id:\` for cursor persistence
2) **Transformer** (optional): \`.pipe((data) => ...)\` to reshape
3) **Target**: \`.pipeTo(...)\` to persist with rollback safety

Keep the pipeline linear and declarative. Combine multiple decoders by passing a named \`outputs\` record to the portal source — one entry per decoder; \`data.<name>\` picks them apart downstream.

## Query discipline
- Request only fields you need (use Query Builder if you need more than logs/events)
- Use explicit \`range\` and minimize breadth
- Avoid decoding entire datasets without filters

## Persistence discipline
When persisting:
- Use \`onStart\` to ensure tables exist
- Use \`onData\` to batch inserts
- Use \`onRollback\` with the provided \`safeCursor\` to delete rows above the safe point

## Stateful indexing
For long-running jobs, guard against forks:
- Always wire rollback logic in the target
- Treat the cursor as the source of truth for safety

## EVM-specific notes
- Use \`evmStream\` + \`evmEventDecoder\`
- \`commonAbis.erc20\` is available for ERC20 transfers
- For custom contracts, generate ABIs into \`src/contracts/\`
- Use \`contractFactory\` + \`contractFactorySqliteStore\` for dynamic contract sets

## Solana-specific notes
- Use \`solanaPortalStream\`
- Use instruction decoding for program-specific data
- Query builder is the safe way to select accounts, programs, and fields
- Use the latency watcher only when debugging performance

## Quality-of-life patterns
- Add log summaries per batch rather than per event
- Prefer typed events/instructions over raw logs
- For multiple decoders on one source, pass them as a named \`outputs\` record — their results land under \`data.<name>\`

## Docs entry points
- Quickstart: https://docs.sqd.dev/en/sdk/pipes-sdk/evm.autogenerated/quickstart
- Introduction: https://docs.sqd.dev/en/sdk/pipes-sdk/evm.autogenerated/introduction
- Core concepts: https://docs.sqd.dev/en/sdk/pipes-sdk/evm.autogenerated/core-concepts/overview
- Event decoding: https://docs.sqd.dev/en/sdk/pipes-sdk/evm.autogenerated/guides/event-decoding
- Factory pattern: https://docs.sqd.dev/en/sdk/pipes-sdk/evm.autogenerated/guides/factory-pattern
- Data persistence: https://docs.sqd.dev/en/sdk/pipes-sdk/evm.autogenerated/guides/data-persistence

## Examples (trimmed)

### Generate ABIs for custom contracts
Use the ABI type generator when you need typed events for a contract that is not covered by \`commonAbis\`.
Generated files should live under \`src/contracts/\` so they can be imported in \`src/index.ts\`.

\`\`\`sh
npx @subsquid/evm-typegen@latest src/contracts \\
  0x000000000004444c5dc75cB358380D2e3dE08A90 \\
  --chain-id 1
\`\`\`

### Basic EVM stream
Creates a Portal source, decodes ERC20 transfers with the built-in ABI, and logs the batch size.

\`\`\`ts
import { commonAbis, evmEventDecoder, evmStream } from '@subsquid/pipes/evm'

async function main() {
  const stream = evmStream({
    id: 'erc20-transfers',
    source: 'https://portal.sqd.dev/datasets/ethereum-mainnet',
    outputs: evmEventDecoder({
      range: { from: 'latest' },
      events: {
        transfers: commonAbis.erc20.events.Transfer,
      },
    }),
  })

  for await (const { data } of stream) {
    console.log(data.transfers.length)
  }
}

void main()
\`\`\`

### Factory pattern (EVM)
Tracks pools created by a factory contract, then decodes swap events only for those pools.
This is the standard approach for protocols with dynamic contract creation (e.g., Uniswap V3).

\`\`\`ts
import { contractFactory, contractFactorySqliteStore, evmEventDecoder, evmStream } from '@subsquid/pipes/evm'
import { events as factoryAbi } from './abi/uniswap.v3/factory'
import { events as swapsAbi } from './abi/uniswap.v3/swaps'

async function main() {
  const stream = evmStream({
    id: 'uniswap-v3-swaps',
    source: 'https://portal.sqd.dev/datasets/ethereum-mainnet',
    outputs: evmEventDecoder({
      range: { from: '12,369,621' },
      contracts: contractFactory({
        address: '0x1f98431c8ad98523631ae4a59f267346ea31f984',
        event: factoryAbi.PoolCreated,
        childAddressField: 'pool',
        database: contractFactorySqliteStore({ path: './uniswap3-eth-pools.sqlite' }),
      }),
      events: {
        swaps: swapsAbi.Swap,
      },
    }),
  })

  for await (const { data } of stream) {
    console.log(\`parsed \${data.swaps.length} swaps\`)
  }
}

void main()
\`\`\`

### ClickHouse target
Decodes ERC20 transfers, maps them to rows, and writes them to ClickHouse with rollback safety.

\`\`\`ts
import { createClient } from '@clickhouse/client'
import { commonAbis, evmEventDecoder, evmStream } from '@subsquid/pipes/evm'
import { clickhouseTarget } from '@subsquid/pipes/targets/clickhouse'

async function main() {
  await evmStream({
    id: 'erc20-transfers-clickhouse',
    source: 'https://portal.sqd.dev/datasets/ethereum-mainnet',
    outputs: evmEventDecoder({
      range: { from: 'latest' },
      events: {
        transfers: commonAbis.erc20.events.Transfer,
      },
    }),
  })
    .pipe((data) =>
      data.transfers.map((t) => ({
        block_number: t.block.number,
        tx_hash: t.rawEvent.transactionHash,
        log_index: t.rawEvent.logIndex,
        token: t.contract,
        from: t.event.from,
        to: t.event.to,
        amount: t.event.value.toString(),
      })),
    )
    .pipeTo(
      clickhouseTarget({
        client: createClient({
          username: 'default',
          password: 'password',
          url: 'http://localhost:8123',
        }),
        onStart: async ({ store }) => {
          await store.command({
            query: \`
              CREATE TABLE IF NOT EXISTS erc20_transfers (
                block_number  UInt64,
                tx_hash       String,
                log_index     UInt16,
                timestamp     DateTime64(3) CODEC (DoubleDelta, ZSTD),
                token         String,
                from          String,
                to            String,
                amount        UInt256,
                sign          Int8 DEFAULT 1,
                INDEX _sqd_rollback_idx block_number TYPE minmax GRANULARITY 1
              )
              ENGINE = CollapsingMergeTree(sign)
              -- The sorting key must uniquely identify a transfer: CollapsingMergeTree
              -- collapses rows sharing the same key, so a non-unique key loses data
              ORDER BY (block_number, tx_hash, log_index)
            \`,
          })
        },
        onData: async ({ data, store }) => {
          await store.insert({
            table: 'erc20_transfers',
            values: data,
            format: 'JSONEachRow',
          })
        },
        onRollback: async ({ safeCursor, store }) => {
          await store.removeAllRows({
            tables: ['erc20_transfers'],
            where: \`block_number > {latest:UInt32}\`,
            params: { latest: safeCursor.number },
          })
        },
      }),
    )
}

void main()
\`\`\`

`
